name: evira
description: "An e-commerce app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  provider: ^6.1.5
  get_it: ^8.0.3
  equatable: ^2.0.7
  fpdart: ^1.1.1
  go_router: ^15.2.4

  # UI & Animation
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  dotted_border: ^3.0.1
  carousel_slider: ^5.1.1

  # Fonts & Styling
  google_fonts: ^6.2.1

  # Network & Storage
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2

  # Utilities
  flutter_dotenv: ^5.2.1
  logger: ^2.6.0
  intl: ^0.20.2
  toastification: ^3.0.3

  # Backend
  supabase_flutter: ^2.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/bold/
    - assets/icons/outline/
    - assets/icons/colored/
    - assets/animations/
    - assets/images/
    - assets/images/logo/
    - assets/images/promo/

  # fonts:
  #   - family: Trajan Pr
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         style: italic
  #         weight: 700

flutter_intl:
  enabled: true
  class_name: FlutterIntl
  main_locale: en
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#191a1f"
  image: assets/images/logo/light_logo.png
  image_dark: assets/images/logo/dark_logo.png

  android_12:
    color: "#ffffff"
    color_dark: "#191a1f"
    image: assets/images/logo/light_logo.png
    image_dark: assets/images/logo/dark_logo.png

  android: true
  ios: true
  web: false

  android_gravity: center
  ios_content_mode: scaleAspectFill
