name: evira
description: "An e-commerce app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  provider: ^6.1.5
  equatable: ^2.0.7
  get_it: ^8.0.3

  # UI & Animation
  cupertino_icons: ^1.0.8

  # Fonts & Styling
  google_fonts: ^6.2.1

  # Network & Storage
  path_provider: ^2.1.5

  # Utilities
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Trajan Pr
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         style: italic
  #         weight: 700